create table if not exists public.outreach_contacts (
  id bigint generated by default as identity primary key,
  talent_slug text not null unique,
  candidate_name text not null,
  profile_url text not null default '',
  summary text not null default '',
  category text not null default 'unknown',
  stack jsonb not null default '[]'::jsonb,
  message_id bigint,
  message_body text not null default '',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.outreach_contacts enable row level security;

create policy "service can manage outreach contacts"
on public.outreach_contacts
for all
to anon
using (true)
with check (true);